function [u_r,v_r] = ...
    em_vel_rotate(mltref,fh,fz,e1,e2,wef,off_time,e1off,e2off,ang_time,anghxhy)
%em_vel_rotate is used to rotate the E1 and E2 to Cartesian coordinates to
%derive the true velocity field

%Please use the function em_offset_ang.m to generate required field of
%e1off, e2off, and anghxgy
%The time array off_time is associate with the time of e1off and e2off
%The time array ang_time is associate with the time of anghxhy
%
%If the e1off, e2off, and anghxgy are all generated by the function of  em_offset_ang.m
%The mltref, off_time and ang_time are the same
%fh and fz are the horizontal and vertical magnetic field in the unit of nT
%
%mltref is the time array for e1, e2 and wef
%e1 the raw voltage measurements on E1
%e2 the raw voltage measurements on E2
%wef the vertical speed of the floats (upward positive), computed by
%interpolating the vertical speed derived from the CTD measurements

%The current codes are written by Dr. J-Y Hsu in National Taiwan University
%on 11/23/2021

% electrode separation
esep1 = (8+5/8)*0.0254; % m
c1 = 0.5;
c2 = -0.2;
% angles between compass and electrode axes
alpha2 = 1.95;
alpha1 = alpha2 - pi/2;
sfv1 = 1e3/(fz*esep1*(1.0+c1));
sfw = fh/fz*(1.0+c2)/(1.0+c1);
%%
%Change all variable into the same dimension
var_name=char('mltref','e1','e2','wef','off_time','e1off','e2off','ang_time','anghxhy');
for N=1:length(var_name(:,1))
    vars=strtrim(var_name(N,:));
    eval([vars '=' vars '(:);'])
end
%%
%Offset removal
ks=~isnan(off_time)&~isnan(e1off)&~isnan(e2off);
e1_rv=interp1(off_time(ks),e1off(ks),mltref);
e2_rv=interp1(off_time(ks),e2off(ks),mltref);

e1f=e1-e1_rv;
e2f=e2-e2_rv;

ks=~isnan(ang_time)&~isnan(anghxhy);
angi=unwrap(anghxhy);
ang_rs=interp1(ang_time(ks),angi(ks),mltref);
ang_r=atan2(sin(ang_rs),cos(ang_rs));


%%
%Rotate electrode coordinates to the Cartesian coordinates
Ex_r=e1f.*cos(ang_r)-e2f.*sin(ang_r);
Ey_r=e1f.*sin(ang_r)+e2f.*cos(ang_r);


%%
%Adjust the angle between Hx and E1 in order put it back to
%Cartesian coordinates
%H_S means this Jx is toward south
s = sin(alpha1);
c = cos(alpha1);
E_S=Ex_r*c-Ey_r*s;
E_E=Ex_r*s+Ey_r*c;


%%
%Convert east north voltage to velocity unit
%Here still includes beta effect
%Compare to those computed in the Eha and Eza,
%no high-pass filter is applied to the u_r and v_r here
u_r=-E_E*sfv1;
v_r=-E_S*sfv1 + wef * sfw;

return
end

